#!/usr/bin/node

var request = require('request');

var slack_token = 'dBiwpc9oRtRuN9jQYitl9Y27';


var repo = process.argv[2];
var revision = process.argv[3].toString();

var execFile = require('child_process').execFile;
var child = execFile('/usr/bin/svnlook', ['log', repo, '--revision', revision], (error, stdout, stderr) => {
  if (error) {
    throw error;
  }
	const log = stdout;
	var child = execFile('/usr/bin/svnlook', ['author', repo, '--revision', revision], (error, stdout, stderr) => {
		if(error){
			throw error;
		}
		const author = stdout;
		const child = execFile('/usr/bin/svnlook', ['diff', repo, '--revision', revision], (error, stdout, stderr) => {
			const diff = stdout;
			const child = execFile('/usr/bin/svnlook', ['date', repo, '--revision', revision], (error, stdout, stderr) => {
				const datetime = new Date(stdout.slice(0, 19)).getTime();
        var tasks = log.match(/(#[0-9.]*)/ig)
        var task_id = '';
        if(tasks.length > 0){
          task_id = tasks[0].replace('#','');
        }
				// Now I need to post it all to roadtrip
				request.post('http://dev.telegauge.com:3000/roadtrip/revisions', {json:{revision: process.argv[3], log:log, author:author, diff: diff, datetime: datetime, repository: '56fe9a014b88de4618e306c7', task_id: task_id }})

				// Tell slack after we tell roadtrip
				url = "https://telegauge.slack.com/services/hooks/subversion?token="+slack_token;
				request.post(url, {form: { payload: JSON.stringify( {log: log.trim(), author: author.trim(), revision: process.argv[3], url: 'http://dev.telegauge.com:3000/#revisions/view/'+process.argv[3] }) } });

			});
		});

	});
});


//exec("/usr/bin/svnlook author -r $argv[2] $argv[1]", $who);

//$log = implode("\n", $log);
//$who = implode("\n", $who);
